class CMError(Exception): ...
class CMDeviceRegisterError(CMError):
    def __init__(self, bonjour_id: str): ...
class CMCommunicationError(CMError): ...
class CMConfigurationError(CMError): ...
class CMDeviceConfigurationError(CMConfigurationError): ...
class CMManagerConfigurationError(CMConfigurationError): ...
class CMHandlerConfigurationError(CMConfigurationError): ...
class CMTimeout(CMError): ...
class CMHandlerDiscoveryTimeout(CMTimeout):
    def __init__(self, addr: str): ...
class CMBonjourTimeout(CMTimeout):
    def __init__(self, command_id: str): ...
class CMDeviceDiscoveryTimeout(CMError): ...
class CMDeviceReplyTimeout(CMTimeout):
    def __init__(self, device_name: str, command_name: str, elapsed: float): ...
