from .commanddevice import CommandDevice

def limit_value(value: int) -> int: ...

class CommandNeoPixel(CommandDevice):
    def __init__(self): ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def set_color(self, red: int, green: int, blue: int) -> None: ...
    def set_brightness(self, brightness: int) -> None: ...
