from typing import Tuple

from .commanddevice import CommandDevice


class CommandTCS34725(CommandDevice):
    def set_integration_time(self, integration_time: float) -> None: ...
    def set_gain(self, gain: int) -> None: ...
    def get_rgbc(self) -> Tuple[int, int, int, int]: ...
    def get_initialization_code(self) -> int: ...
